### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by codemajor247** [pranavpandey/dynamic-toasts#5]
Dear support . 
this library rtl supported !?

**Comment by pranavpandey** [comment]
Yes, as I have designed the layout accordingly.

You can test it by setting any RTL language for your phone and then, install this [sample](https://github.com/pranavpandey/dynamic-toasts/releases/download/v2.1.1/dynamic-toasts.apk).
 It will automatically flip the layout for toast and hint.

I think, that's all you want?

**Comment by pranavpandey** [comment]
Added RTL support for text. It will be available soon in the next update.
