### ISSUE TITLE
How to change text color?

### ISSUE THREAD

**Issue by IshaanKr** [pranavpandey/dynamic-toasts#6]

**Comment by IshaanKr** [comment]
.setDefaultTintColor(@ColorInt int defaultTintColor)

**Comment by IshaanKr** [comment]
Not able to set .setDefaultTintColor(android.R.color.white)

**Comment by IshaanKr** [comment]
Not with DynamicToast.make(context, char, drawable, android.R.color.white, android.R.color.black, duration)

**Comment by IshaanKr** [comment]
i want to add white text on different background colors

**Comment by pranavpandey** [comment]
You are using color `resource id` while the `color integer` is expected. 

You can use any of the below methods to get the color integer:

```java
// By using the support library.
ContextCompat.getColor(context, android.R.color.white)

OR

// By using the context.
context.getColor(android.R.color.white)

OR

// By parsing the hexadecimal string.
Color.parseColor("#FFFFFF")
```

Please check the [sample](https://github.com/pranavpandey/dynamic-toasts/blob/df23382d7a26c060ca1572582051bdc286155330/sample/src/main/java/com/pranavpandey/android/dynamic/toasts/sample/DynamicToastsActivity.kt#L125) for more info.
